/*
 * FrmPrincipal.java
 *
 * Created on 12 de Março de 2006, 10:05
 */

package net.softlages.gui;

/**
 *
 * @author  Cliente
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    /** Creates new form FrmPrincipal */
    public FrmPrincipal() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        setor = new javax.swing.JMenuItem();
        funcionario = new javax.swing.JMenuItem();
        miDependente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        sair = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        relFuncionarios = new javax.swing.JMenuItem();
        relFuncionariosPorSalario = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Funcion\u00e1rios - Java Developer");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Controle de Funcion\u00e1rios");
        getContentPane().add(jLabel1, java.awt.BorderLayout.SOUTH);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/softlages/icons/home_nav.gif")));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToolBar1.add(jToggleButton1);

        jToolBar1.add(jLabel2);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/softlages/icons/showerr_tsk.gif")));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToolBar1.add(jToggleButton2);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/softlages/icons/java.png")));
        jButton1.setEnabled(false);
        jPanel1.add(jButton1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        menuCadastro.setMnemonic('C');
        menuCadastro.setText("Cadastro");
        menuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroActionPerformed(evt);
            }
        });

        setor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.CTRL_MASK));
        setor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/softlages/icons/home_nav.gif")));
        setor.setMnemonic('S');
        setor.setText("Setor");
        setor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setorActionPerformed(evt);
            }
        });

        menuCadastro.add(setor);

        funcionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        funcionario.setMnemonic('F');
        funcionario.setText("Funcion\u00e1rio");
        funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionarioActionPerformed(evt);
            }
        });

        menuCadastro.add(funcionario);

        miDependente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        miDependente.setMnemonic('D');
        miDependente.setText("Dependente");
        miDependente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDependenteActionPerformed(evt);
            }
        });

        menuCadastro.add(miDependente);

        menuCadastro.add(jSeparator1);

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/softlages/icons/showerr_tsk.gif")));
        sair.setMnemonic('S');
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        menuCadastro.add(sair);

        jMenuBar1.add(menuCadastro);

        menuConsultas.setMnemonic('o');
        menuConsultas.setText("Consultas");
        relFuncionarios.setText("Relat\u00f3rio de funcion\u00e1rios");
        relFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relFuncionariosActionPerformed(evt);
            }
        });

        menuConsultas.add(relFuncionarios);

        relFuncionariosPorSalario.setMnemonic('S');
        relFuncionariosPorSalario.setText("Funcion\u00e1rio por Sal\u00e1rio");
        relFuncionariosPorSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relFuncionariosPorSalarioActionPerformed(evt);
            }
        });

        menuConsultas.add(relFuncionariosPorSalario);

        jMenuBar1.add(menuConsultas);

        menuAjuda.setMnemonic('A');
        menuAjuda.setText("Ajuda");
        jMenuBar1.add(menuAjuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miDependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDependenteActionPerformed
       new CadastroDependente(this,true).setVisible(true);
    }//GEN-LAST:event_miDependenteActionPerformed

    private void relFuncionariosPorSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relFuncionariosPorSalarioActionPerformed
 
    }//GEN-LAST:event_relFuncionariosPorSalarioActionPerformed

    private void relFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relFuncionariosActionPerformed

    }//GEN-LAST:event_relFuncionariosActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        sair.doClick();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionarioActionPerformed
        CadastroFuncionario cf = new CadastroFuncionario(this,true);
        cf.setVisible(true);
    }//GEN-LAST:event_funcionarioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void setorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setorActionPerformed
        CadastroSetor cs = new CadastroSetor(this,true);
        cs.setVisible(true);
    }//GEN-LAST:event_setorActionPerformed
    
    
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
    }//GEN-LAST:event_jToggleButton1ActionPerformed
    
    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed
    
    private void menuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroActionPerformed

    }//GEN-LAST:event_menuCadastroActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }
    
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JMenuItem funcionario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenuItem miDependente;
    private javax.swing.JMenuItem relFuncionarios;
    private javax.swing.JMenuItem relFuncionariosPorSalario;
    private javax.swing.JMenuItem sair;
    private javax.swing.JMenuItem setor;
    // Fim da declaração de variáveis//GEN-END:variables
    
}
