package gui;


import excecoes.ExcecaoReservatorio;
import java.text.DecimalFormat;
import model.Controle;
import model.EnumPrecoCombustivel;
import model.EnumPrecoOleo;
import model.Nota;
import model.Reservatorio;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aluno
 */
public class Posto extends javax.swing.JFrame {
    Nota nota = new Nota();
    DecimalFormat df = new DecimalFormat("0.00");
    /**
     * Creates new form Posto
     */
    public Posto() {
        initComponents();
        
        // mostrando valores da tabela de preço de combustivel      
        this.tfPrecoDiesel.setText("R$ " + EnumPrecoCombustivel.OLEO_DIESEL.getValor());
        this.ftPrecoComum.setText("R$ " + EnumPrecoCombustivel.GAS_COMUM.getValor());
        this.tfPrecoAditivada.setText("R$ " + EnumPrecoCombustivel.GAS_ADITIVADA.getValor());
        this.tfPrecoAlcool.setText("R$ " + EnumPrecoCombustivel.ALCOOL.getValor());
        
         // mostrando valores da tabela de preço de oleo
        this.tfPrecoPequeno.setText("R$ " + EnumPrecoOleo.OLEO500.getValor());
        this.tfPrecoGrande.setText("R$ " + EnumPrecoOleo.OLEO1000.getValor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAbastecimento = new javax.swing.ButtonGroup();
        bgPagamento = new javax.swing.ButtonGroup();
        pnTabelaPrecoCombustivel = new javax.swing.JPanel();
        lbPrecoDiesel = new javax.swing.JLabel();
        lbPrecoComum = new javax.swing.JLabel();
        lbPrecoAditivada = new javax.swing.JLabel();
        lbPrecoAlcool = new javax.swing.JLabel();
        tfPrecoDiesel = new javax.swing.JTextField();
        ftPrecoComum = new javax.swing.JTextField();
        tfPrecoAditivada = new javax.swing.JTextField();
        tfPrecoAlcool = new javax.swing.JTextField();
        pnTabelaPrecoOleo = new javax.swing.JPanel();
        lbPrecoPequeno = new javax.swing.JLabel();
        lbPrecoGrande = new javax.swing.JLabel();
        tfPrecoPequeno = new javax.swing.JTextField();
        tfPrecoGrande = new javax.swing.JTextField();
        Abastecimento = new javax.swing.JPanel();
        rbAbastDiesel = new javax.swing.JRadioButton();
        rbAbastComum = new javax.swing.JRadioButton();
        rbAbastAditivada = new javax.swing.JRadioButton();
        rbAbastAlcool = new javax.swing.JRadioButton();
        lbAbastQtdLitros = new javax.swing.JLabel();
        lbAbastTotalCombustivel = new javax.swing.JLabel();
        tfAbastQtdLitros = new javax.swing.JTextField();
        ftAbastTotalCombustivel = new javax.swing.JTextField();
        btReservatorios = new javax.swing.JButton();
        pnOleoMotor = new javax.swing.JPanel();
        cbOleoPequeno = new javax.swing.JCheckBox();
        cbOleoGrande = new javax.swing.JCheckBox();
        lbOleoQtd = new javax.swing.JLabel();
        lbOleoValor = new javax.swing.JLabel();
        lbOleoTotal = new javax.swing.JLabel();
        tfOleoQtdPequeno = new javax.swing.JTextField();
        tfOleoQtdGrande = new javax.swing.JTextField();
        tfOleoValorPequeno = new javax.swing.JTextField();
        tfOleoValorGrande = new javax.swing.JTextField();
        tfOleoTotal = new javax.swing.JTextField();
        pnFormaPagamento = new javax.swing.JPanel();
        rbPagamentoAvista = new javax.swing.JRadioButton();
        rbPagamentoPrazo = new javax.swing.JRadioButton();
        lbPagamentoDias = new javax.swing.JLabel();
        tfPagamentoDias = new javax.swing.JTextField();
        lbPagamentoTotal = new javax.swing.JLabel();
        btPagamentoObservacoes = new javax.swing.JButton();
        tfPagamentoTotal = new javax.swing.JTextField();
        pnBotoes = new javax.swing.JPanel();
        btCalcular = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnTabelaPrecoCombustivel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabela de Preço do Combustível", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lbPrecoDiesel.setText("Óleo Diesel:");

        lbPrecoComum.setText("Gas. Comum:");

        lbPrecoAditivada.setText("Gas. Aditivada:");

        lbPrecoAlcool.setText("Álcool:");

        tfPrecoDiesel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrecoDieselActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTabelaPrecoCombustivelLayout = new javax.swing.GroupLayout(pnTabelaPrecoCombustivel);
        pnTabelaPrecoCombustivel.setLayout(pnTabelaPrecoCombustivelLayout);
        pnTabelaPrecoCombustivelLayout.setHorizontalGroup(
            pnTabelaPrecoCombustivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTabelaPrecoCombustivelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTabelaPrecoCombustivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPrecoAditivada)
                    .addComponent(lbPrecoAlcool)
                    .addComponent(lbPrecoComum)
                    .addComponent(lbPrecoDiesel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTabelaPrecoCombustivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfPrecoDiesel, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(ftPrecoComum)
                    .addComponent(tfPrecoAditivada)
                    .addComponent(tfPrecoAlcool))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnTabelaPrecoCombustivelLayout.setVerticalGroup(
            pnTabelaPrecoCombustivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTabelaPrecoCombustivelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTabelaPrecoCombustivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrecoDiesel)
                    .addComponent(tfPrecoDiesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTabelaPrecoCombustivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrecoComum)
                    .addComponent(ftPrecoComum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTabelaPrecoCombustivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrecoAditivada)
                    .addComponent(tfPrecoAditivada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTabelaPrecoCombustivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrecoAlcool)
                    .addComponent(tfPrecoAlcool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnTabelaPrecoOleo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabela de Preço de Óleo Motor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lbPrecoPequeno.setText("Frasco 500ml:");

        lbPrecoGrande.setText("Frasco 1l:");

        javax.swing.GroupLayout pnTabelaPrecoOleoLayout = new javax.swing.GroupLayout(pnTabelaPrecoOleo);
        pnTabelaPrecoOleo.setLayout(pnTabelaPrecoOleoLayout);
        pnTabelaPrecoOleoLayout.setHorizontalGroup(
            pnTabelaPrecoOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTabelaPrecoOleoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTabelaPrecoOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPrecoPequeno)
                    .addComponent(lbPrecoGrande))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTabelaPrecoOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPrecoGrande, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnTabelaPrecoOleoLayout.createSequentialGroup()
                        .addComponent(tfPrecoPequeno, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnTabelaPrecoOleoLayout.setVerticalGroup(
            pnTabelaPrecoOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTabelaPrecoOleoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnTabelaPrecoOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrecoPequeno)
                    .addComponent(tfPrecoPequeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTabelaPrecoOleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPrecoGrande)
                    .addComponent(tfPrecoGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Abastecimento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Abastecimento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        bgAbastecimento.add(rbAbastDiesel);
        rbAbastDiesel.setText("Óleo Diesel");

        bgAbastecimento.add(rbAbastComum);
        rbAbastComum.setText("Gas. Comum");

        bgAbastecimento.add(rbAbastAditivada);
        rbAbastAditivada.setText("Gas. Aditivada");

        bgAbastecimento.add(rbAbastAlcool);
        rbAbastAlcool.setText("Álcool");

        lbAbastQtdLitros.setText("Quantidade Litros:");

        lbAbastTotalCombustivel.setText("Total Combustível:");

        tfAbastQtdLitros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfAbastQtdLitrosKeyReleased(evt);
            }
        });

        ftAbastTotalCombustivel.setEditable(false);
        ftAbastTotalCombustivel.setText("0");

        btReservatorios.setText("Reservatórios");
        btReservatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReservatoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AbastecimentoLayout = new javax.swing.GroupLayout(Abastecimento);
        Abastecimento.setLayout(AbastecimentoLayout);
        AbastecimentoLayout.setHorizontalGroup(
            AbastecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbastecimentoLayout.createSequentialGroup()
                .addGroup(AbastecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbastecimentoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(rbAbastDiesel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(rbAbastComum, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(rbAbastAditivada, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AbastecimentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AbastecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAbastQtdLitros)
                            .addComponent(lbAbastTotalCombustivel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AbastecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfAbastQtdLitros, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(ftAbastTotalCombustivel))
                        .addGap(93, 93, 93)))
                .addGroup(AbastecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btReservatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AbastecimentoLayout.createSequentialGroup()
                        .addComponent(rbAbastAlcool, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AbastecimentoLayout.setVerticalGroup(
            AbastecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbastecimentoLayout.createSequentialGroup()
                .addGroup(AbastecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbAbastDiesel)
                    .addComponent(rbAbastComum)
                    .addGroup(AbastecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbAbastAditivada)
                        .addComponent(rbAbastAlcool)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AbastecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAbastQtdLitros)
                    .addComponent(tfAbastQtdLitros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AbastecimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAbastTotalCombustivel)
                    .addComponent(ftAbastTotalCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btReservatorios))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnOleoMotor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Óleo Motor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        cbOleoPequeno.setText("Frasco de 500ml");
        cbOleoPequeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOleoPequenoActionPerformed(evt);
            }
        });

        cbOleoGrande.setText("Frasco de 1l");
        cbOleoGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOleoGrandeActionPerformed(evt);
            }
        });

        lbOleoQtd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbOleoQtd.setText("Quantidade");

        lbOleoValor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbOleoValor.setText("Valor a Pagar");

        lbOleoTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbOleoTotal.setText("Total Óleo");

        tfOleoQtdPequeno.setEditable(false);
        tfOleoQtdPequeno.setText("0");
        tfOleoQtdPequeno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfOleoQtdPequenoKeyReleased(evt);
            }
        });

        tfOleoQtdGrande.setEditable(false);
        tfOleoQtdGrande.setText("0");
        tfOleoQtdGrande.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfOleoQtdGrandeKeyReleased(evt);
            }
        });

        tfOleoValorPequeno.setEditable(false);
        tfOleoValorPequeno.setText("0");

        tfOleoValorGrande.setEditable(false);
        tfOleoValorGrande.setText("0");

        tfOleoTotal.setEditable(false);
        tfOleoTotal.setText("0");

        javax.swing.GroupLayout pnOleoMotorLayout = new javax.swing.GroupLayout(pnOleoMotor);
        pnOleoMotor.setLayout(pnOleoMotorLayout);
        pnOleoMotorLayout.setHorizontalGroup(
            pnOleoMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOleoMotorLayout.createSequentialGroup()
                .addGroup(pnOleoMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbOleoPequeno)
                    .addComponent(cbOleoGrande))
                .addGap(41, 41, 41)
                .addGroup(pnOleoMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbOleoQtd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfOleoQtdPequeno)
                    .addComponent(tfOleoQtdGrande))
                .addGap(52, 52, 52)
                .addGroup(pnOleoMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbOleoValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfOleoValorPequeno)
                    .addComponent(tfOleoValorGrande))
                .addGap(40, 40, 40)
                .addGroup(pnOleoMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbOleoTotal)
                    .addComponent(tfOleoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnOleoMotorLayout.setVerticalGroup(
            pnOleoMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOleoMotorLayout.createSequentialGroup()
                .addGroup(pnOleoMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbOleoQtd)
                    .addComponent(lbOleoValor)
                    .addComponent(lbOleoTotal))
                .addGap(4, 4, 4)
                .addGroup(pnOleoMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbOleoPequeno)
                    .addComponent(tfOleoQtdPequeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfOleoValorPequeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfOleoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnOleoMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbOleoGrande)
                    .addComponent(tfOleoQtdGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfOleoValorGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnFormaPagamento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Forma de pagamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        bgPagamento.add(rbPagamentoAvista);
        rbPagamentoAvista.setText("A vista");
        rbPagamentoAvista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPagamentoAvistaActionPerformed(evt);
            }
        });

        bgPagamento.add(rbPagamentoPrazo);
        rbPagamentoPrazo.setText("Prazo");
        rbPagamentoPrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPagamentoPrazoActionPerformed(evt);
            }
        });

        lbPagamentoDias.setText("Dias:");

        tfPagamentoDias.setEditable(false);

        lbPagamentoTotal.setText("Total a pagar:");

        btPagamentoObservacoes.setText("Abrir observações");
        btPagamentoObservacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPagamentoObservacoesActionPerformed(evt);
            }
        });

        tfPagamentoTotal.setEditable(false);
        tfPagamentoTotal.setText("0");

        javax.swing.GroupLayout pnFormaPagamentoLayout = new javax.swing.GroupLayout(pnFormaPagamento);
        pnFormaPagamento.setLayout(pnFormaPagamentoLayout);
        pnFormaPagamentoLayout.setHorizontalGroup(
            pnFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormaPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFormaPagamentoLayout.createSequentialGroup()
                        .addComponent(rbPagamentoAvista)
                        .addGap(18, 18, 18)
                        .addComponent(rbPagamentoPrazo)
                        .addGap(28, 28, 28)
                        .addComponent(lbPagamentoDias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPagamentoDias, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btPagamentoObservacoes))
                    .addGroup(pnFormaPagamentoLayout.createSequentialGroup()
                        .addComponent(lbPagamentoTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPagamentoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnFormaPagamentoLayout.setVerticalGroup(
            pnFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFormaPagamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbPagamentoAvista)
                    .addComponent(rbPagamentoPrazo)
                    .addComponent(lbPagamentoDias)
                    .addComponent(tfPagamentoDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPagamentoObservacoes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnFormaPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbPagamentoTotal)
                    .addComponent(tfPagamentoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });
        pnBotoes.add(btCalcular);

        btNovo.setText("Novo Cálculo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        pnBotoes.add(btNovo);

        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });
        pnBotoes.add(btFechar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Abastecimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnTabelaPrecoCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnTabelaPrecoOleo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnOleoMotor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnFormaPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTabelaPrecoCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnTabelaPrecoOleo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Abastecimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(pnOleoMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPagamentoObservacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPagamentoObservacoesActionPerformed
        // TODO add your handling code here:
        new DialogObservacoes(this, true).setVisible(true);
    }//GEN-LAST:event_btPagamentoObservacoesActionPerformed

    private void tfAbastQtdLitrosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAbastQtdLitrosKeyReleased
        // TODO add your handling code here:
        nota.setQtdLitros(Double.parseDouble(tfAbastQtdLitros.getText()));
        
        if (rbAbastDiesel.isSelected()) {
            nota.setCombustivel(EnumPrecoCombustivel.OLEO_DIESEL);
            nota.setTotalCombustivel(EnumPrecoCombustivel.OLEO_DIESEL.getValor()*nota.getQtdLitros());
        }
        if (rbAbastComum.isSelected()){
            nota.setCombustivel(EnumPrecoCombustivel.GAS_COMUM);
            nota.setTotalCombustivel(EnumPrecoCombustivel.GAS_COMUM.getValor()*nota.getQtdLitros());
        }
        if (rbAbastAditivada.isSelected()){
            nota.setCombustivel(EnumPrecoCombustivel.GAS_ADITIVADA);
            nota.setTotalCombustivel(EnumPrecoCombustivel.GAS_ADITIVADA.getValor()*nota.getQtdLitros());
        }
        if (rbAbastAlcool.isSelected()){
            nota.setCombustivel(EnumPrecoCombustivel.ALCOOL);
            nota.setTotalCombustivel(EnumPrecoCombustivel.ALCOOL.getValor()*nota.getQtdLitros());
        }
        this.ftAbastTotalCombustivel.setText("R$ " + df.format(nota.getTotalCombustivel()));
        //String aux = ftAbastTotalCombustivel.getText().replace("R$ ", "").replace(",",".");
        //System.out.println("Aux " + aux);
        //double v = Double.parseDouble(aux);
    }//GEN-LAST:event_tfAbastQtdLitrosKeyReleased

    private void tfOleoQtdPequenoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfOleoQtdPequenoKeyReleased
        // TODO add your handling code here:
        nota.setTotal500(EnumPrecoOleo.OLEO500.getValor() * Double.parseDouble(tfOleoQtdPequeno.getText()));
        this.tfOleoValorPequeno.setText("R$ " + df.format(nota.getTotal500()));
        nota.setTotalOleo(nota.getTotal1000()+nota.getTotal500());
        this.tfOleoTotal.setText("R$ " + df.format(nota.getTotalOleo()));
    }//GEN-LAST:event_tfOleoQtdPequenoKeyReleased

    private void tfOleoQtdGrandeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfOleoQtdGrandeKeyReleased
        // TODO add your handling code here:
        nota.setTotal1000(EnumPrecoOleo.OLEO1000.getValor() * Double.parseDouble(tfOleoQtdGrande.getText()));
        this.tfOleoValorGrande.setText("R$ " + df.format(nota.getTotal1000()));
        nota.setTotalOleo(nota.getTotal1000()+nota.getTotal500());
        this.tfOleoTotal.setText("R$ " + df.format(nota.getTotalOleo()));
    }//GEN-LAST:event_tfOleoQtdGrandeKeyReleased

    private void cbOleoPequenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOleoPequenoActionPerformed
        // TODO add your handling code here:
        if (cbOleoPequeno.isSelected()) {
            this.tfOleoQtdPequeno.setEditable(true);
            this.tfOleoQtdPequeno.requestFocus();
            
        } else {
            this.tfOleoQtdPequeno.setEditable(false);
        }
    }//GEN-LAST:event_cbOleoPequenoActionPerformed

    private void cbOleoGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOleoGrandeActionPerformed
        // TODO add your handling code here:
        if (cbOleoGrande.isSelected()) {
            this.tfOleoQtdGrande.setEditable(true);
            this.tfOleoQtdGrande.requestFocus();
            
        } else {
            this.tfOleoQtdGrande.setEditable(false);
        }
    }//GEN-LAST:event_cbOleoGrandeActionPerformed

    private void rbPagamentoAvistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPagamentoAvistaActionPerformed

    }//GEN-LAST:event_rbPagamentoAvistaActionPerformed

    private void rbPagamentoPrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPagamentoPrazoActionPerformed
        // TODO add your handling code here:
        if (rbPagamentoPrazo.isSelected()) {
            nota.setAvista(false);
            this.tfPagamentoDias.setEditable(true);
            this.tfPagamentoDias.requestFocus();
        }
            
    }//GEN-LAST:event_rbPagamentoPrazoActionPerformed

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        // TODO add your handling code here:
        if (rbPagamentoAvista.isSelected()) {
            nota.setAvista(true);
            double desconto = (nota.getTotalCombustivel())*0.1;
            nota.setTotal(nota.getTotalOleo() + nota.getTotalCombustivel() - desconto);
            this.tfPagamentoTotal.setText("R$ " + df.format(nota.getTotal()));        
        }
        else if (rbPagamentoPrazo.isSelected()) {
            nota.setDias(Integer.parseInt(this.tfPagamentoDias.getText()));
            if (nota.getDias() > 30) {
                double acrescimo = (nota.getTotalOleo()+nota.getTotalCombustivel())*0.1;
                nota.setTotal(nota.getTotalOleo() + nota.getTotalCombustivel() + acrescimo);
                this.tfPagamentoTotal.setText("R$ " + df.format(nota.getTotal()));        
            }
            else {
                nota.setTotal(nota.getTotalOleo() + nota.getTotalCombustivel());
                this.tfPagamentoTotal.setText("R$ " + df.format(nota.getTotal()));
            }
        }
        
        if (rbAbastDiesel.isSelected()) {
            try {
                Controle.resDiesel.saida(nota.getQtdLitros());
            } catch (ExcecaoReservatorio er) {
                new DialogError(this, true, er.getMessage()).setVisible(true);
              }
        }
        if (rbAbastComum.isSelected()){
             try {
                Controle.resComum.saida(nota.getQtdLitros());
            } catch (ExcecaoReservatorio er) {
                new DialogError(this, true, er.getMessage()).setVisible(true);
              }
        }
        if (rbAbastAditivada.isSelected()){
             try {
                Controle.resAditivada.saida(nota.getQtdLitros());
            } catch (ExcecaoReservatorio er) {
                new DialogError(this, true, er.getMessage()).setVisible(true);
              }
        }
        if (rbAbastAlcool.isSelected()){
            nota.setCombustivel(EnumPrecoCombustivel.ALCOOL);
            nota.setTotalCombustivel(EnumPrecoCombustivel.ALCOOL.getValor()*nota.getQtdLitros());
             try {
                Controle.resAlcool.saida(nota.getQtdLitros());
            } catch (ExcecaoReservatorio er) {
                new DialogError(this, true, er.getMessage()).setVisible(true);
              }
        }
    }//GEN-LAST:event_btCalcularActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        bgAbastecimento.clearSelection();
        bgPagamento.clearSelection();
        this.tfAbastQtdLitros.setText("");
        this.tfOleoQtdPequeno.setText("");
        this.tfOleoQtdGrande.setText("");
        this.tfPagamentoDias.setText("");
        this.ftAbastTotalCombustivel.setText("0");
        this.tfOleoValorPequeno.setText("0");
        this.tfOleoValorGrande.setText("0");
        this.tfOleoTotal.setText("0");
        this.tfPagamentoTotal.setText("0");
        this.cbOleoPequeno.setSelected(false);
        this.cbOleoGrande.setSelected(false);
        
       
    }//GEN-LAST:event_btNovoActionPerformed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btFecharActionPerformed

    private void tfPrecoDieselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrecoDieselActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrecoDieselActionPerformed

    private void btReservatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReservatoriosActionPerformed
        // TODO add your handling code here:
         new DialogControle(this, true).setVisible(true);
    }//GEN-LAST:event_btReservatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Posto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Posto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Posto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Posto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Posto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Abastecimento;
    private javax.swing.ButtonGroup bgAbastecimento;
    private javax.swing.ButtonGroup bgPagamento;
    private javax.swing.JButton btCalcular;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPagamentoObservacoes;
    private javax.swing.JButton btReservatorios;
    private javax.swing.JCheckBox cbOleoGrande;
    private javax.swing.JCheckBox cbOleoPequeno;
    private javax.swing.JTextField ftAbastTotalCombustivel;
    private javax.swing.JTextField ftPrecoComum;
    private javax.swing.JLabel lbAbastQtdLitros;
    private javax.swing.JLabel lbAbastTotalCombustivel;
    private javax.swing.JLabel lbOleoQtd;
    private javax.swing.JLabel lbOleoTotal;
    private javax.swing.JLabel lbOleoValor;
    private javax.swing.JLabel lbPagamentoDias;
    private javax.swing.JLabel lbPagamentoTotal;
    private javax.swing.JLabel lbPrecoAditivada;
    private javax.swing.JLabel lbPrecoAlcool;
    private javax.swing.JLabel lbPrecoComum;
    private javax.swing.JLabel lbPrecoDiesel;
    private javax.swing.JLabel lbPrecoGrande;
    private javax.swing.JLabel lbPrecoPequeno;
    private javax.swing.JPanel pnBotoes;
    private javax.swing.JPanel pnFormaPagamento;
    private javax.swing.JPanel pnOleoMotor;
    private javax.swing.JPanel pnTabelaPrecoCombustivel;
    private javax.swing.JPanel pnTabelaPrecoOleo;
    private javax.swing.JRadioButton rbAbastAditivada;
    private javax.swing.JRadioButton rbAbastAlcool;
    private javax.swing.JRadioButton rbAbastComum;
    private javax.swing.JRadioButton rbAbastDiesel;
    private javax.swing.JRadioButton rbPagamentoAvista;
    private javax.swing.JRadioButton rbPagamentoPrazo;
    private javax.swing.JTextField tfAbastQtdLitros;
    private javax.swing.JTextField tfOleoQtdGrande;
    private javax.swing.JTextField tfOleoQtdPequeno;
    private javax.swing.JTextField tfOleoTotal;
    private javax.swing.JTextField tfOleoValorGrande;
    private javax.swing.JTextField tfOleoValorPequeno;
    private javax.swing.JTextField tfPagamentoDias;
    private javax.swing.JTextField tfPagamentoTotal;
    private javax.swing.JTextField tfPrecoAditivada;
    private javax.swing.JTextField tfPrecoAlcool;
    private javax.swing.JTextField tfPrecoDiesel;
    private javax.swing.JTextField tfPrecoGrande;
    private javax.swing.JTextField tfPrecoPequeno;
    // End of variables declaration//GEN-END:variables
}
